/**
 * Bindings, as declared in `wrangler.jsonc`.
 *
 * The shape itself is generated by `wrangler types` into `worker-configuration.d.ts`; this
 * alias exists so the rest of the code has one import to point at, and one place to read what
 * each binding is for:
 *
 *   CAL           KV namespace holding the catalogue, snapshots and cohort registrations.
 *   CRAWL_TOKEN   Shared secret guarding `/__parse` and `/__crawl`.
 *                 `wrangler secret put CRAWL_TOKEN`.
 *   PUBLIC_ORIGIN Public origin. Calendar UIDs are anchored to it, so changing it after
 *                 people have subscribed duplicates every event in their calendars.
 *   SELF          Service binding pointing back at this Worker, so internal endpoints run as
 *                 separate invocations with their own CPU budget.
 */
export type Env = Cloudflare.Env & Partial<OperatorVars>;

/**
 * Who runs this instance.
 *
 * Deliberately not in the source: whoever deploys a fork is the operator of *their* instance
 * and must appear in *their* Impressum. Hard-coding one person's address would put it on
 * every fork's legal pages and into the User-Agent the crawler shows the university, so a
 * question about the crawl would reach the wrong person.
 *
 * Set with `wrangler secret put OPERATOR_NAME` and so on. Secrets rather than `vars` because
 * `wrangler.jsonc` lives in the repository.
 */
export interface OperatorVars {
  OPERATOR_NAME: string;
  OPERATOR_STREET: string;
  OPERATOR_CITY: string;
  OPERATOR_EMAIL: string;
}

export interface Operator {
  name: string;
  street: string;
  city: string;
  email: string;
}

const OPERATOR_KEYS: (keyof OperatorVars)[] = [
  'OPERATOR_NAME', 'OPERATOR_STREET', 'OPERATOR_CITY', 'OPERATOR_EMAIL',
];

/**
 * Reads the operator details, or reports which ones are missing.
 *
 * All or nothing: a partly filled Impressum is worth no more than an empty one, so anything
 * incomplete counts as unconfigured and the legal pages say so instead of showing half an
 * address.
 */
export function readOperator(env: Env): { operator: Operator | null; missing: string[] } {
  const missing = OPERATOR_KEYS.filter((k) => (env[k] ?? '').trim() === '');
  if (missing.length > 0) return { operator: null, missing };
  return {
    operator: {
      name: env.OPERATOR_NAME!.trim(),
      street: env.OPERATOR_STREET!.trim(),
      city: env.OPERATOR_CITY!.trim(),
      email: env.OPERATOR_EMAIL!.trim(),
    },
    missing: [],
  };
}
